---
- hosts: webservers
  become: true
  tasks:
     - name: installing the httpd server.
       yum:
         name: "httpd"
         state: "present"
     - name: starting the service.
       service:
         name: httpd
         state: started
